# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAutoLoginSquareSpace():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_autoLoginSquareSpace(self):
    self.driver.get("https://login.squarespace.com/api/1/login/oauth/provider/authorize?client_id=qNgYXXcY8Fa8M&redirect_uri=https%3A%2F%2Fwww.squarespace.com%2Fauth%2Foauth%2Fconnect%3FdestinationUrl%3Dhttps%253A%252F%252Fwww.squarespace.com%252Fauth%252Fprotected-redirect%252Flogin%253Flocation%253Dhttps%25253A%25252F%25252Faccount.squarespace.com&state=1%3A1580876142%3AfP08x6hg3IVPuRcr9ZiIq1zEN05Q6NSkQQtqatO04aQ%3D&overrideLocale=en-US&options=%7B%22isCloseVisible%22%3Atrue%2C%22isCreateAccountViewActive%22%3Afalse%7D#/")
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.NAME, "email")))
    self.driver.find_element(By.NAME, "email").send_keys(self.vars["usernameVar"])
    self.driver.find_element(By.NAME, "password").send_keys(self.vars["passwordVar"])
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    WebDriverWait(self.driver, 10000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"sentinel-username-error\"]")))
    self.vars["alertText"] = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"sentinel-username-error\"]").text
    print(str(self.vars["alertText"]))
    if self.driver.execute_script("return (arguments[0] == \'Please enter a valid email address or username.\')", self.vars["alertText"]):
      print(str("No good"))
    else:
      self.vars["self.vars["credentialsFound"] | SquareSpace"] = "self.vars["credentialsFound"]"
      print(str("I\'m in!!!!"))
  
