# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAutoLoginDisney():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_autoLoginDisney(self):
    self.driver.get("https://www.disneyplus.com/login")
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.ID, "email")))
    self.driver.find_element(By.ID, "email").send_keys("fdsafsad@fdsafsd.com")
    self.driver.find_element(By.NAME, "dssLoginSubmit").click()
    self.vars["alertText"] = self.driver.find_element(By.CSS_SELECTOR, ".kVdxYn").text
    if self.driver.execute_script("return (arguments[0] == \'TRY AGAIN\')", self.vars["alertText"]):
      print(str("No good"))
    else:
      self.vars["self.vars["credentialsFound"] | Disney+"] = "self.vars["credentialsFound"]"
      print(str("I\'m in!!!!"))
  
