# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAutoLoginSpotify():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_autoLoginSpotify(self):
    self.driver.get("https://accounts.spotify.com/en/login/?continue=https:%2F%2Fwww.spotify.com%2Fus%2Faccount%2Foverview%2F&_locale=en-US")
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.ID, "login-username")))
    self.driver.find_element(By.ID, "login-username").send_keys(self.vars["usernameVar"])
    self.driver.find_element(By.ID, "login-password").send_keys(self.vars["passwordVar"])
    self.driver.find_element(By.ID, "login-button").click()
    WebDriverWait(self.driver, 10000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".alert")))
    self.vars["alertText"] = self.driver.find_element(By.CSS_SELECTOR, ".alert > .ng-binding").text
    if self.driver.execute_script("return (arguments[0] == \'Incorrect username or password.\')", self.vars["alertText"]):
      print(str("No good"))
    else:
      self.vars["self.vars["credentialsFound"] | Spotify"] = "self.vars["credentialsFound"]"
      print(str("I\'m in!!!!"))
  
