# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAutoLoginHBONow():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_autoLoginHBONow(self):
    self.driver.get("https://play.hbonow.com/page/urn:hbo:page:home")
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".default:nth-child(5) > .default:nth-child(2) > .default > span > span")))
    self.driver.find_element(By.CSS_SELECTOR, ".default:nth-child(5) > .default:nth-child(2) > .default > span > span").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//input[@type=\'text\']")))
    self.driver.find_element(By.XPATH, "//input[@type=\'text\']").send_keys(self.vars["usernameVar"])
    self.driver.find_element(By.XPATH, "//input[@type=\'password\']").send_keys(self.vars["passwordVar"])
    self.driver.find_element(By.XPATH, "//div[8]/div/div[6]/div").click()
    self.vars["alertText"] = self.driver.find_element(By.CSS_SELECTOR, ".class2 > span > span").text
    if self.driver.execute_script("return (arguments[0] == \'The email address or password is incorrect. Please try again.\')", self.vars["alertText"]):
      print(str("No good"))
    else:
      self.vars["self.vars["credentialsFound"] | HBO Now"] = "self.vars["credentialsFound"]"
      print(str("I\'m in!!!!"))
  
