# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAutoLoginSteam():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_autoLoginSteam(self):
    self.driver.get("https://store.steampowered.com/login/")
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.ID, "input_username")))
    self.driver.find_element(By.ID, "input_username").send_keys(self.vars["usernameVar"])
    self.driver.find_element(By.ID, "input_password").send_keys(self.vars["passwordVar"])
    self.driver.find_element(By.CSS_SELECTOR, "#login_btn_signin span").click()
    WebDriverWait(self.driver, 10000).until(expected_conditions.visibility_of_element_located((By.ID, "input_password")))
    if self.driver.execute_script("return (id=input_password)"):
      print(str("No good"))
    else:
      self.vars["self.vars["credentialsFound"] | Steam"] = "self.vars["credentialsFound"]"
      print(str("I\'m in!!!!"))
  
