# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAutoLoginATTTV():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_autoLoginATTTV(self):
    self.driver.get("https://cprodmasx.att.com/commonLogin/igate_wam/controller.do?TAM_OP=login&USERNAME=unauthenticated&ERROR_CODE=0x00000000&ERROR_TEXT=HPDBA0521I%20%20%20Successful%20completion&METHOD=GET&URL=%2Fpkmsvouchfor%3FATT%26https%3A%2F%2Fcprodx.att.com%2FTokenService%2FnxsATS%2FWATokenService%3FisPassive%3Dfalse%26lang%3Den%26appID%3Dm14961%26returnURL%3Dhttps%253A%252F%252Fapi.cld.dtvce.com%252Faccount%252Faeg%252Fums%252Ftglogin%253FnextUrl%253Dhttps%25253A%25252F%25252Fwww.atttvnow.com%25252Faccounts%25252Fsign-in&REFERER=https%3A%2F%2Fwww.atttvnow.com%2Faccounts%2Fsign-in&HOSTNAME=cprodmasx.att.com&AUTHNLEVEL=&FAILREASON=&OLDSESSION=")
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.ID, "userName")))
    self.driver.find_element(By.ID, "userName").send_keys(self.vars["usernameVar"])
    self.driver.find_element(By.ID, "password").send_keys(self.vars["passwordVar"])
    self.driver.find_element(By.ID, "loginButton-lgwgLoginButton").click()
    WebDriverWait(self.driver, 10000).until(expected_conditions.visibility_of_element_located((By.ID, "password")))
    if self.driver.execute_script("return (id=password)"):
      print(str("No good"))
    else:
      self.vars["self.vars["credentialsFound"] | ATT TV"] = "self.vars["credentialsFound"]"
      print(str("I\'m in!!!!"))
  
